# Use the official PostgreSQL image as the base image
FROM postgres:latest

# Set environment variables
ENV POSTGRES_DB=grepp-backend
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=password

# Copy dump file
COPY ./scripts/dump.sql /docker-entrypoint-initdb.d/

# Expose the PostgreSQL port
EXPOSE 5432

# Set the default command to run when starting the container
CMD ["postgres"]
