version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - app-network
    environment:
      - PYTHONPATH=/app
      - POSTGRES_USER=postgres
      - POSTGRES_PWD=password
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=grepp-backend
      - DATABASE_URL=postgresql://postgres:password@db:5432/grepp-backend
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=grepp-backend
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
