# 공식 Python 런타임을 부모 이미지로 사용
FROM python:3.9

# 작업 디렉토리를 /app으로 설정
WORKDIR /app

# 현재 디렉토리의 내용을 컨테이너의 /app에 복사
COPY . /app

# 필요한 패키지 설치
RUN pip install --no-cache-dir -r requirements/base.txt

# 환경 변수 설정
ENV PYTHONPATH=/app

# 시작 스크립트 실행
CMD ["/bin/bash", "/app/start.sh"]
