"""add index

Revision ID: 8fb15993f9f4
Revises: 41e60ead2983
Create Date: 2024-10-10 14:03:53.978045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fb15993f9f4'
down_revision: Union[str, None] = '41e60ead2983'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_exam_schedules_start_time'), 'exam_schedules', ['start_time'], unique=False)
    op.create_index(op.f('ix_reservations_is_confirmed'), 'reservations', ['is_confirmed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservations_is_confirmed'), table_name='reservations')
    op.drop_index(op.f('ix_exam_schedules_start_time'), table_name='exam_schedules')
    # ### end Alembic commands ###
